application: hjelpetekst
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /demo
  static_dir: demo
  secure: always

- url: /js
  static_dir: js
  secure: always

- url: /.*
  script: hjelpetekst.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"